import Head from "next/head";
import { Elsie_Swash_Caps } from "@next/font/google";
import HTMLFlipBook from "react-pageflip";
import { forwardRef, ReactNode, useEffect, useState } from "react";

const bodyFont = Elsie_Swash_Caps({ weight: ["400"] });

export const Page = forwardRef<HTMLDivElement, { children: ReactNode }>(
  ({ children }, ref) => {
    return (
      <div ref={ref} className="relative overflow-hidden">
        <div
          className="absolute -inset-2 bg-yellow-50"
          style={{
            boxShadow: "2px 3px 20px black, 0 0 60px #8a4d0f inset",
            filter: "url(#wavy)",
          }}
        ></div>
        <div className="absolute inset-0">{children}</div>
      </div>
    );
  }
);

export const FadedImage = ({
  src = "/images/kitty-1.png",
}: {
  src?: string;
}) => {
  return (
    <div className="relative">
      <div
        className="absolute -inset-2 border-yellow-50 border-[20px]"
        style={{ filter: "url(#wavy-edges)" }}
      />
      <img width="280px" src={src} />
    </div>
  );
};

export default function Home() {
  const [dimensions, setDimensions] = useState({
    width: 800,
    height: 600,
  });

  useEffect(() => {
    setDimensions({ height: window.innerHeight, width: window.innerWidth });
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-full overflow-hidden relative">
        <svg className="hidden">
          <filter id="wavy">
            <feTurbulence
              x="0"
              y="0"
              baseFrequency="0.02"
              numOctaves="5"
              seed="1"
            ></feTurbulence>
            <feDisplacementMap in="SourceGraphic" scale="10" />
          </filter>
        </svg>
        <svg className="hidden">
          <filter id="wavy-edges">
            <feTurbulence
              x="0"
              y="0"
              baseFrequency="0.02"
              numOctaves="5"
              seed="1"
            ></feTurbulence>
            <feDisplacementMap in="SourceGraphic" scale="16" />
          </filter>
        </svg>
        {/* @ts-ignore */}
        <HTMLFlipBook width={450} height={600} maxShadowOpacity={0.3}>
          <Page>
            <div className="w-full flex flex-col items-center justify-center px-12 py-16">
              <FadedImage src="/images/pretty-princess.png" />
              <div className={`${bodyFont.className} text-xl py-10`}>
                Once upon a time, in a far-off land, there was a beautiful
                princess named Rose. Rose lived in a grand castle with her
                parents, the king and queen, and her little brother, Prince
                Jack.
              </div>
            </div>
          </Page>
          <Page>
            <div className="w-full flex flex-col items-center justify-center px-12 py-16">
              <div className={`${bodyFont.className} text-xl pb-10`}>
                Rose loved nothing more than exploring the castle gardens and
                playing with her pet dragon, Sparky. Sparky was a mischievous
                little dragon, always getting into trouble and causing chaos
                wherever he went.
              </div>
              <FadedImage />
            </div>
          </Page>
          <Page>
            <div className="w-full flex flex-col items-center justify-center px-12 py-16">
              <FadedImage src="/images/dragon-fire.png" />
              <div className={`${bodyFont.className} text-xl py-10`}>
                One day, while Rose and Sparky were out for a stroll, they
                stumbled upon a hidden treasure map. Excited by the prospect of
                finding treasure, Rose and Sparky set off on an adventure to
                find the treasure.
              </div>
            </div>
          </Page>
          <Page>
            <div className="w-full flex flex-col items-center justify-center px-12 py-16">
              <FadedImage />
              <div className={`${bodyFont.className} text-xl py-10`}>
                They followed the map through the dense forest, over babbling
                brooks, and across rolling hills. Along the way, they met all
                sorts of interesting creatures, like talking rabbits, singing
                birds, and even a friendly giant.
              </div>
            </div>
          </Page>
          <Page>
            <div className="w-full flex flex-col items-center justify-center px-12 py-16">
              <FadedImage />
              <div className={`${bodyFont.className} text-xl py-10`}>
                Finally, after many days of travel, Rose and Sparky arrived at
                the treasure's hiding place: a mysterious cave deep in the
                mountains. They braved the dark, winding tunnels, determined to
                find the treasure.
              </div>
            </div>
          </Page>
          <Page>
            <div className="w-full flex flex-col items-center justify-center px-12 py-16">
              <FadedImage />
              <div className={`${bodyFont.className} text-xl py-10`}>
                And at last, they found it: a chest full of glittering jewels,
                sparkling diamonds, and shining gold. Rose and Sparky were
                overjoyed by their discovery, and they knew that they would
                always be the best of friends, no matter what adventure came
                their way. The end.
              </div>
            </div>
          </Page>
        </HTMLFlipBook>
      </main>
    </>
  );
}
